Steal testing setup from ankane/groupdate
Pushing groupdate compaitibility back to 3.0.0

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -2,6 +2,9 @@
 set -euo pipefail
 IFS=$'\n\t'
 
+echo "Installing gems..."
 bundle install
-
-# Do any other automated setup that you need to do here
+echo "Creating postgres database..."
+createdb calculate_all_test || echo "...failed"
+echo "Creating mysql database..."
+mysqladmin -u root create calculate_all_test || echo "...failed"
